### ISSUE TITLE
how to install conpy by anaconda

### ISSUE THREAD

**Issue by Iv911** [wmvanvliet/conpy#1]
when run 'pip install https://github.com/wmvanvliet/conpy/zipball/master',  i got a error:      
 File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-5qdm7gdd-build\setup.py", line 17, in <module>
        long_description=open('README.md').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 4882: illegal multibyte sequence

how to solve it?

**Comment by wmvanvliet** [comment]
That looks like a text encoding problem. Thanks for reporting. Let's see if we can debug this.
First, can you tell me which Python version you are using?

**Comment by Iv911** [comment]
The problem about install may still unsolved. 
After debuged, I can install the module of "conpy", but i got a warning when input "conpy.csd_epochs(epochs,frequencies, tmin =0, tmax = 0.4, decim = 20)", the warning is "module 'conpy' has no attribute 'csd_epochs'".

ps The Python version i used is 3.6.4.



mj846067412@qq.com
 
From: Marijn van Vliet
Date: 2018-07-04 15:24
To: wmvanvliet/conpy
CC: Iv911; Author
Subject: Re: [wmvanvliet/conpy] how to install conpy by anaconda (#1)
I've change the offending line of code to make the text encoding explicit (0d72f50). Can you try it now?
―

**Comment by wmvanvliet** [comment]
conpy no longer has a `csd_epochs` function. Please use [`mne.time_frequency.csd_morlet`](https://www.martinos.org/mne/stable/generated/mne.time_frequency.csd_morlet.html). See also the latest version of the preprint of the paper:

https://www.biorxiv.org/content/early/2018/01/16/245530

**Comment by wmvanvliet** [comment]
conpy no longer has a `csd_epochs` function. Please use [`mne.time_frequency.csd_morlet`](https://www.martinos.org/mne/stable/generated/mne.time_frequency.csd_morlet.html). See also the latest version of the preprint of the paper:

https://www.biorxiv.org/content/early/2018/01/16/245530
